namespace Ana.Source.Scanners.BackgroundScans.Prefilters
{
    using ActionScheduler;
    using Engine;
    using Engine.OperatingSystems;
    using Engine.Processes;
    using Output;
    using Snapshots;
    using System;
    using System.Collections.Generic;
    using System.Threading;
    using Utils.DataStructures;
    using Utils.Extensions;

    /// <summary>
    /// Class to collect all pointers in the module bases of the target process, and slowly trace pointers from there.
    /// The growth radius will be small, so only a small subset of the processes memory should be explored.
    /// </summary>
    internal class ShallowPointerPrefilter : ScheduledTask, ISnapshotPrefilter
    {
        /// <summary>
        /// The distance from the pointer target where we will keep the addresses in this prefilter.
        /// </summary>
        private const Int32 PointerRadius = 2048;

        /// <summary>
        /// The maximum number of regions to process in a given update cycle.
        /// </summary>
        private const Int32 RegionLimit = 8192;

        /// <summary>
        /// The time between each update cycle.
        /// </summary>
        private const Int32 RescanTime = 4096;

        /// <summary>
        /// Singleton instance of the <see cref="ShallowPointerPrefilter"/> class.
        /// </summary>
        private static Lazy<ISnapshotPrefilter> snapshotPrefilterInstance = new Lazy<ISnapshotPrefilter>(
            () => { return new ShallowPointerPrefilter(); },
            LazyThreadSafetyMode.ExecutionAndPublication);

        /// <summary>
        /// Gets or sets the number of regions processed by this prefilter.
        /// </summary>
        private Int64 processedCount;

        /// <summary>
        /// Prevents a default instance of the <see cref="ShallowPointerPrefilter" /> class from being created.
        /// </summary>
        private ShallowPointerPrefilter() : base(isRepeated: true)
        {
            this.PrefilteredSnapshot = new Snapshot();
            this.RegionLock = new Object();
            this.processedCount = 0;
        }

        /// <summary>
        /// Gets or sets a lock for accessing snapshot regions.
        /// </summary>
        private Object RegionLock { get; set; }

        /// <summary>
        /// Gets or sets the snapshot constructed by this prefilter.
        /// </summary>
        private Snapshot PrefilteredSnapshot { get; set; }

        /// <summary>
        /// Gets a singleton instance of the <see cref="ShallowPointerPrefilter"/> class.
        /// </summary>
        /// <returns>A singleton instance of the class.</returns>
        public static ISnapshotPrefilter GetInstance()
        {
            return ShallowPointerPrefilter.snapshotPrefilterInstance.Value;
        }

        /// <summary>
        /// Starts the update cycle for this prefilter.
        /// </summary>
        public void BeginPrefilter()
        {
            this.Begin();
        }

        /// <summary>
        /// Gets the snapshot generated by the prefilter.
        /// </summary>
        /// <returns>The snapshot generated by the prefilter.</returns>
        public Snapshot GetPrefilteredSnapshot()
        {
            lock (this.RegionLock)
            {
                return this.PrefilteredSnapshot.Clone();
            }
        }

        /// <summary>
        /// Recieves a process update.
        /// </summary>
        /// <param name="process">The newly selected process.</param>>
        public void Update(NormalizedProcess process)
        {
            lock (this.RegionLock)
            {
                if (this.PrefilteredSnapshot.ByteCount > 0)
                {
                    this.PrefilteredSnapshot = new Snapshot();
                    OutputViewModel.GetInstance().Log(OutputViewModel.LogLevel.Info, "Pointer Prefilter cleared");
                }
            }
        }

        /// <summary>
        /// Starts the prefilter.
        /// </summary>
        protected override void OnBegin()
        {
            this.UpdateInterval = ShallowPointerPrefilter.RescanTime;
        }

        /// <summary>
        /// Updates the prefilter.
        /// </summary>
        protected override void OnUpdate()
        {
            this.ProcessPages();
            this.UpdateProgress();
        }

        /// <summary>
        /// Processes all pages, computing checksums to determine chunks of virtual pages that have changed.
        /// </summary>
        private void ProcessPages()
        {
            Boolean isOpenedProcess32Bit = EngineCore.GetInstance().Processes.IsOpenedProcess32Bit();
            dynamic invalidPointerMin = isOpenedProcess32Bit ? (UInt32)UInt16.MaxValue : (UInt64)UInt16.MaxValue;
            dynamic invalidPointerMax = isOpenedProcess32Bit ? Int32.MaxValue : Int64.MaxValue;
            ConcurrentHashSet<IntPtr> foundPointers = new ConcurrentHashSet<IntPtr>();

            // Add static bases
            List<SnapshotRegion> baseRegions = new List<SnapshotRegion>();
            foreach (NormalizedModule normalizedModule in EngineCore.GetInstance().OperatingSystemAdapter.GetModules())
            {
                baseRegions.Add(new SnapshotRegion(normalizedModule.BaseAddress, normalizedModule.RegionSize));
            }

            ((dynamic)this.PrefilteredSnapshot).AddSnapshotRegions(baseRegions);

            lock (this.RegionLock)
            {
                List<SnapshotRegion> pointerRegions = new List<SnapshotRegion>();

                foreach (IntPtr pointer in PointerCollector.GetInstance().GetFoundPointers())
                {
                    pointerRegions.Add(new SnapshotRegion(pointer.Subtract(ShallowPointerPrefilter.PointerRadius), ShallowPointerPrefilter.PointerRadius * 2));
                }

               ((dynamic)this.PrefilteredSnapshot).AddSnapshotRegions(pointerRegions);
                this.processedCount = Math.Max(this.processedCount, this.PrefilteredSnapshot.GetRegionCount());
            }
        }

        /// <summary>
        /// Updates the progress of how many regions have been processed.
        /// </summary>
        private void UpdateProgress()
        {
            Int32 regionCount = 1;

            lock (this.RegionLock)
            {
                if (this.PrefilteredSnapshot != null)
                {
                    regionCount = Math.Max(regionCount, this.PrefilteredSnapshot.GetRegionCount());
                }
            }
        }
    }
    //// End class
}
//// End namespace