//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squalr.Engine.Scanning.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class ScanSettings : global::System.Configuration.ApplicationSettingsBase
    {
        private static ScanSettings defaultInstance = ((ScanSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ScanSettings())));

        public static ScanSettings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int FreezeInterval
        {
            get
            {
                return ((int)(this["FreezeInterval"]));
            }
            set
            {
                this["FreezeInterval"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int RescanInterval
        {
            get
            {
                return ((int)(this["RescanInterval"]));
            }
            set
            {
                this["RescanInterval"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ResultReadInterval
        {
            get
            {
                return ((int)(this["ResultReadInterval"]));
            }
            set
            {
                this["ResultReadInterval"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TableReadInterval
        {
            get
            {
                return ((int)(this["TableReadInterval"]));
            }
            set
            {
                this["TableReadInterval"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemoryTypeNone
        {
            get
            {
                return ((bool)(this["MemoryTypeNone"]));
            }
            set
            {
                this["MemoryTypeNone"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemoryTypePrivate
        {
            get
            {
                return ((bool)(this["MemoryTypePrivate"]));
            }
            set
            {
                this["MemoryTypePrivate"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemoryTypeImage
        {
            get
            {
                return ((bool)(this["MemoryTypeImage"]));
            }
            set
            {
                this["MemoryTypeImage"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MemoryTypeMapped
        {
            get
            {
                return ((bool)(this["MemoryTypeMapped"]));
            }
            set
            {
                this["MemoryTypeMapped"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int InputCorrelatorTimeOutInterval
        {
            get
            {
                return ((int)(this["InputCorrelatorTimeOutInterval"]));
            }
            set
            {
                this["InputCorrelatorTimeOutInterval"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Alignment
        {
            get
            {
                return ((int)(this["Alignment"]));
            }
            set
            {
                this["Alignment"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RequiredWrite
        {
            get
            {
                return ((bool)(this["RequiredWrite"]));
            }
            set
            {
                this["RequiredWrite"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RequiredExecute
        {
            get
            {
                return ((bool)(this["RequiredExecute"]));
            }
            set
            {
                this["RequiredExecute"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RequiredCopyOnWrite
        {
            get
            {
                return ((bool)(this["RequiredCopyOnWrite"]));
            }
            set
            {
                this["RequiredCopyOnWrite"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExcludedWrite
        {
            get
            {
                return ((bool)(this["ExcludedWrite"]));
            }
            set
            {
                this["ExcludedWrite"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExcludedExecute
        {
            get
            {
                return ((bool)(this["ExcludedExecute"]));
            }
            set
            {
                this["ExcludedExecute"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExcludedCopyOnWrite
        {
            get
            {
                return ((bool)(this["ExcludedCopyOnWrite"]));
            }
            set
            {
                this["ExcludedCopyOnWrite"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong StartAddress
        {
            get
            {
                return ((ulong)(this["StartAddress"]));
            }
            set
            {
                this["StartAddress"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9223372036854775807")]
        public ulong EndAddress
        {
            get
            {
                return ((ulong)(this["EndAddress"]));
            }
            set
            {
                this["EndAddress"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUserMode
        {
            get
            {
                return ((bool)(this["IsUserMode"]));
            }
            set
            {
                this["IsUserMode"] = value;
            }
        }
    }
}
