namespace Squalr.Engine.Architecture.Assembler
{
    using System;

    /// <summary>
    /// The Masm assembler for x86/64.
    /// </summary>
    internal class MasmAssembler : IAssembler
    {
        /// <summary>
        /// Assemble the specified assembly code.
        /// </summary>
        /// <param name="isProcess32Bit">Whether or not the assembly is in the context of a 32 bit program.</param>
        /// <param name="assembly">The assembly code.</param>
        /// <param name="message">The logs generated by the assembler.</param>
        /// <returns>An array of bytes containing the assembly code.</returns>
        public AssemblerResult Assemble(Boolean isProcess32Bit, String assembly)
        {
            // Assemble and return the code
            return this.Assemble(isProcess32Bit, assembly, IntPtr.Zero);
        }

        /// <summary>
        /// Assemble the specified assembly code at a base address.
        /// </summary>
        /// <param name="isProcess32Bit">Whether or not the assembly is in the context of a 32 bit program.</param>
        /// <param name="assembly">The assembly code.</param>
        /// <param name="baseAddress">The address where the code is rebased.</param>
        /// <returns>An array of bytes containing the assembly code.</returns>
        public AssemblerResult Assemble(Boolean isProcess32Bit, String assembly, IntPtr baseAddress)
        {
            AssemblerResult result = null;

            return result;
        }
    }
    //// End class
}
//// End namespace