// <auto-generated>
//     This code was generated by the .NET ToolStrip Customizer.
//     http://toolstripcustomizer.codeplex.com/
// </auto-generated>

using System.Drawing;
using System.Windows.Forms;

namespace WeifenLuo.WinFormsUI.Docking
{
    public class VS2015DarkColorTable : ProfessionalColorTable
    {
        public override Color ButtonSelectedHighlight
        {
            get { return ButtonSelectedGradientMiddle; }
        }
        public override Color ButtonSelectedHighlightBorder
        {
            get { return ButtonSelectedBorder; }
        }
        public override Color ButtonPressedHighlight
        {
            get { return ButtonPressedGradientMiddle; }
        }
        public override Color ButtonPressedHighlightBorder
        {
            get { return ButtonPressedBorder; }
        }
        public override Color ButtonCheckedHighlight
        {
            get { return ButtonCheckedGradientMiddle; }
        }
        public override Color ButtonCheckedHighlightBorder
        {
            get { return ButtonSelectedBorder; }
        }
        public override Color ButtonPressedBorder
        {
            get { return ButtonSelectedBorder; }
        }
        public override Color ButtonSelectedBorder
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color ButtonCheckedGradientBegin
        { 
            get { return Color.FromArgb(0, 0, 0, 0); }
        }
        public override Color ButtonCheckedGradientMiddle
        { 
            get { return Color.FromArgb(0, 0, 0, 0); }
        }
        public override Color ButtonCheckedGradientEnd
        { 
            get { return Color.FromArgb(0, 0, 0, 0); }
        }
        public override Color ButtonSelectedGradientBegin
        { 
            get { return Color.FromArgb(255, 62, 62, 64); }
        }
        public override Color ButtonSelectedGradientMiddle
        { 
            get { return Color.FromArgb(255, 62, 62, 64); }
        }
        public override Color ButtonSelectedGradientEnd
        { 
            get { return Color.FromArgb(255, 62, 62, 64); }
        }
        public override Color ButtonPressedGradientBegin
        { 
            get { return Color.FromArgb(255, 0, 122, 204); }
        }
        public override Color ButtonPressedGradientMiddle
        { 
            get { return Color.FromArgb(255, 0, 122, 204); }
        }
        public override Color ButtonPressedGradientEnd
        { 
            get { return Color.FromArgb(255, 0, 122, 204); }
        }
        public override Color CheckBackground
        { 
            get { return Color.FromArgb(255, 27, 27, 28); }
        }
        public override Color CheckSelectedBackground
        { 
            get { return Color.FromArgb(255, 62, 62, 64); }
        }
        public override Color CheckPressedBackground
        { 
            get { return Color.FromArgb(255, 62, 62, 64); }
        }
        public override Color GripDark
        { 
            get { return Color.FromArgb(255, 62, 62, 66); }
        }
        public override Color GripLight
        { 
            get { return Color.FromArgb(255, 62, 62, 66); }
        }
        public override Color ImageMarginGradientBegin
        { 
            get { return Color.FromArgb(255, 27, 27, 28); }
        }
        public override Color ImageMarginGradientMiddle
        { 
            get { return Color.FromArgb(255, 27, 27, 28); }
        }
        public override Color ImageMarginGradientEnd
        { 
            get { return Color.FromArgb(255, 27, 27, 28); }
        }
        public override Color ImageMarginRevealedGradientBegin
        { 
            get { return Color.FromArgb(255, 249, 249, 249); }
        }
        public override Color ImageMarginRevealedGradientMiddle
        { 
            get { return Color.FromArgb(255, 245, 245, 245); }
        }
        public override Color ImageMarginRevealedGradientEnd
        { 
            get { return Color.FromArgb(255, 242, 242, 242); }
        }
        public override Color MenuStripGradientBegin
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color MenuStripGradientEnd
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color MenuItemSelected
        { 
            get { return Color.FromArgb(255, 62, 62, 64); }
        }
        public override Color MenuItemBorder
        { 
            get { return Color.FromArgb(255, 62, 62, 64); }
        }
        public override Color MenuBorder
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color MenuItemSelectedGradientBegin
        { 
            get { return Color.FromArgb(255, 62, 62, 64); }
        }
        public override Color MenuItemSelectedGradientEnd
        { 
            get { return Color.FromArgb(255, 62, 62, 64); }
        }
        public override Color MenuItemPressedGradientBegin
        { 
            get { return Color.FromArgb(255, 27, 27, 28); }
        }
        public override Color MenuItemPressedGradientMiddle
        { 
            get { return Color.FromArgb(255, 27, 27, 28); }
        }
        public override Color MenuItemPressedGradientEnd
        { 
            get { return Color.FromArgb(255, 27, 27, 28); }
        }
        public override Color RaftingContainerGradientBegin
        { 
            get { return Color.FromName("ButtonFace"); }
        }
        public override Color RaftingContainerGradientEnd
        { 
            get { return Color.FromArgb(255, 252, 252, 252); }
        }
        public override Color SeparatorDark
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color SeparatorLight
        { 
            get { return Color.FromArgb(255, 62, 62, 64); }
        }
        public override Color StatusStripGradientBegin
        { 
            get { return Color.FromArgb(255, 0, 122, 204); }
        }
        public override Color StatusStripGradientEnd
        { 
            get { return Color.FromArgb(255, 0, 122, 204); }
        }
        public override Color ToolStripBorder
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color ToolStripDropDownBackground
        { 
            get { return Color.FromArgb(255, 27, 27, 28); }
        }
        public override Color ToolStripGradientBegin
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color ToolStripGradientMiddle
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color ToolStripGradientEnd
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color ToolStripContentPanelGradientBegin
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color ToolStripContentPanelGradientEnd
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color ToolStripPanelGradientBegin
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color ToolStripPanelGradientEnd
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color OverflowButtonGradientBegin
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color OverflowButtonGradientMiddle
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public override Color OverflowButtonGradientEnd
        { 
            get { return Color.FromArgb(255, 45, 45, 48); }
        }
        public Color MenuItemText
        {
            get { return ForeColor; }
        }
        public Color ForeColor
        {
            get { return Color.FromArgb(255, 220, 220, 220); }
        }
        public Color BackColor
        {
            get { return Color.FromArgb(255, 30, 30, 30); }
        }
    }
}